export const mockEvent = [
  {
    start: [2021, 10, 30, 6, 30],
    duration: { hours: 6, minutes: 30 },
    title: "Bolder Boulder",
    description: "Annual 10-kilometer run in Boulder, Colorado",
    location: "Folsom Field, University of Colorado (finish line)",
    url: "http://www.bolderboulder.com/",
    geo: { lat: 40.0095, lon: 105.2669 },
    categories: ["10k races", "Memorial Day Weekend", "Boulder CO"],
    status: "CONFIRMED",
    busyStatus: "BUSY",
    organizer: { name: "Admin", email: "Race@BolderBOULDER.com" },
    attendees: [
      {
        name: "Adam Gibbons",
        email: "adam@example.com",
        rsvp: true,
        partstat: "ACCEPTED",
        role: "REQ-PARTICIPANT",
      },
    ],
  },
];

export const mockUserSchedules = [
  {
    created_at: "Thu, 07 Oct 2021 14:01:18 GMT",
    id: "615efdaea4fd317044ab8e85",
    name: "Plan A",
    schedule_items: [
      {
        course_name: "Analisis Numerik",
        day: "Senin",
        end: "09.40",
        lecturer: [
          " Prof. Drs. T. Basaruddin, M.Sc., Ph.D.",
          " Raja Oktovin Parhasian Damanik, S.Kom., M.Sc.",
        ],
        name: "Analisis Numerik A",
        room: "A2.06 (Ged Baru)",
        sks: 3,
        start: "08.00",
      },
      {
        course_name: "Analisis Numerik",
        day: "Rabu",
        end: "10.50",
        lecturer: [
          " Prof. Drs. T. Basaruddin, M.Sc., Ph.D.",
          " Raja Oktovin Parhasian Damanik, S.Kom., M.Sc.",
        ],
        name: "Analisis Numerik A",
        room: "A2.06 (Ged Baru)",
        sks: 3,
        start: "10.00",
      },
      {
        course_name: "Basis Data",
        day: "Selasa",
        end: "11.40",
        lecturer: [" Mei Silviana Saputri, S.Kom., M.Kom."],
        name: "Basis Data A",
        room: "A1.07 (Ged Baru)",
        sks: 4,
        start: "10.00",
      },
      {
        course_name: "Basis Data",
        day: "Kamis",
        end: "11.40",
        lecturer: [" Mei Silviana Saputri, S.Kom., M.Kom."],
        name: "Basis Data A",
        room: "A1.07 (Ged Baru)",
        sks: 4,
        start: "10.00",
      },
      {
        course_name: "Dasar-Dasar Pemrograman 1",
        day: "Selasa",
        end: "09.40",
        lecturer: [" Drs. Lim Yohanes Stefanus, M.Math, Ph.D."],
        name: "DDP 1 A",
        room: "2.2304",
        sks: 4,
        start: "08.00",
      },
      {
        course_name: "Dasar-Dasar Pemrograman 1",
        day: "Kamis",
        end: "09.40",
        lecturer: [" Drs. Lim Yohanes Stefanus, M.Math, Ph.D."],
        name: "DDP 1 A",
        room: "2.2304",
        sks: 4,
        start: "08.00",
      },
      {
        course_name: "Dasar-Dasar Pemrograman 1",
        day: "Jumat",
        end: "15.40",
        lecturer: [" Drs. Lim Yohanes Stefanus, M.Math, Ph.D."],
        name: "DDP 1 A",
        room: "Lab.1101/1103",
        sks: 4,
        start: "14.00",
      },
      {
        course_name: "Desain & Analisis Algoritma",
        day: "Senin",
        end: "14.40",
        lecturer: [" Theresia Veronika Rampisela, S.Si., M.Kom."],
        name: "DAA A",
        room: "A2.06 (Ged Baru)",
        sks: 4,
        start: "13.00",
      },
      {
        course_name: "Desain & Analisis Algoritma",
        day: "Rabu",
        end: "09.40",
        lecturer: [" Theresia Veronika Rampisela, S.Si., M.Kom."],
        name: "DAA A",
        room: "A2.06 (Ged Baru)",
        sks: 4,
        start: "08.00",
      },
      {
        course_name: "Jaringan Komputer",
        day: "Rabu",
        end: "16.40",
        lecturer: [" Muhammad Hafizhuddin Hilman, S.Kom., M.Kom."],
        name: "Jaringan Komputer B",
        room: "A2.06 (Ged Baru)",
        sks: 4,
        start: "15.00",
      },
      {
        course_name: "Jaringan Komputer",
        day: "Jumat",
        end: "11.40",
        lecturer: [" Muhammad Hafizhuddin Hilman, S.Kom., M.Kom."],
        name: "Jaringan Komputer B",
        room: "A2.06 (Ged Baru)",
        sks: 4,
        start: "10.00",
      },
    ],
  },
];

export const mockFormattedSchedule = {
  "Analisis Numerik-Analisis Numerik A": {
    name: "Analisis Numerik A",
    time: [
      {
        start: "08.00",
        end: "09.40",
        day: "Senin",
        room: "A2.06 (Ged Baru)",
      },
      {
        start: "10.00",
        end: "10.50",
        day: "Rabu",
        room: "A2.06 (Ged Baru)",
      },
    ],
    lecturer: [
      " Prof. Drs. T. Basaruddin, M.Sc., Ph.D.",
      " Raja Oktovin Parhasian Damanik, S.Kom., M.Sc.",
    ],
    sks: 3,
  },
  "Basis Data-Basis Data A": {
    name: "Basis Data A",
    time: [
      {
        start: "10.00",
        end: "11.40",
        day: "Selasa",
        room: "A1.07 (Ged Baru)",
      },
      {
        start: "10.00",
        end: "11.40",
        day: "Kamis",
        room: "A1.07 (Ged Baru)",
      },
    ],
    lecturer: [" Mei Silviana Saputri, S.Kom., M.Kom."],
    sks: 4,
  },
  "Dasar-Dasar Pemrograman 1-DDP 1 A": {
    name: "Dasar-Dasar Pemrograman 1 - DDP 1 A",
    time: [
      {
        start: "08.00",
        end: "09.40",
        day: "Selasa",
        room: "2.2304",
      },
      {
        start: "08.00",
        end: "09.40",
        day: "Kamis",
        room: "2.2304",
      },
      {
        start: "14.00",
        end: "15.40",
        day: "Jumat",
        room: "Lab.1101/1103",
      },
    ],
    lecturer: [" Drs. Lim Yohanes Stefanus, M.Math, Ph.D."],
    sks: 4,
  },
  "Desain & Analisis Algoritma-DAA A": {
    name: "Desain & Analisis Algoritma - DAA A",
    time: [
      {
        start: "13.00",
        end: "14.40",
        day: "Senin",
        room: "A2.06 (Ged Baru)",
      },
      {
        start: "08.00",
        end: "09.40",
        day: "Rabu",
        room: "A2.06 (Ged Baru)",
      },
    ],
    lecturer: [" Theresia Veronika Rampisela, S.Si., M.Kom."],
    sks: 4,
  },
  "Jaringan Komputer-Jaringan Komputer B": {
    name: "Jaringan Komputer B",
    time: [
      {
        start: "15.00",
        end: "16.40",
        day: "Rabu",
        room: "A2.06 (Ged Baru)",
      },
      {
        start: "10.00",
        end: "11.40",
        day: "Jumat",
        room: "A2.06 (Ged Baru)",
      },
    ],
    lecturer: [" Muhammad Hafizhuddin Hilman, S.Kom., M.Kom."],
    sks: 4,
  },
};

export const mockFormattedScheduleToEvent = [
  {
    start: [2021, 10, 4, 8, 0],
    end: [2021, 10, 4, 9, 40],
    title: "Analisis Numerik A",
    location: "A2.06 (Ged Baru)",
  },
  {
    start: [2021, 10, 6, 10, 0],
    end: [2021, 10, 6, 10, 50],
    title: "Analisis Numerik A",
    location: "A2.06 (Ged Baru)",
  },
  {
    start: [2021, 10, 5, 10, 0],
    end: [2021, 10, 5, 11, 40],
    title: "Basis Data A",
    location: "A1.07 (Ged Baru)",
  },
  {
    start: [2021, 10, 7, 10, 0],
    end: [2021, 10, 7, 11, 40],
    title: "Basis Data A",
    location: "A1.07 (Ged Baru)",
  },
  {
    start: [2021, 10, 5, 8, 0],
    end: [2021, 10, 5, 9, 40],
    title: "Dasar-Dasar Pemrograman 1 - DDP 1 A",
    location: "2.2304",
  },
  {
    start: [2021, 10, 7, 8, 0],
    end: [2021, 10, 7, 9, 40],
    title: "Dasar-Dasar Pemrograman 1 - DDP 1 A",
    location: "2.2304",
  },
  {
    start: [2021, 10, 8, 14, 0],
    end: [2021, 10, 8, 15, 40],
    title: "Dasar-Dasar Pemrograman 1 - DDP 1 A",
    location: "Lab.1101/1103",
  },
  {
    start: [2021, 10, 4, 13, 0],
    end: [2021, 10, 4, 14, 40],
    title: "Desain & Analisis Algoritma - DAA A",
    location: "A2.06 (Ged Baru)",
  },
  {
    start: [2021, 10, 6, 8, 0],
    end: [2021, 10, 6, 9, 40],
    title: "Desain & Analisis Algoritma - DAA A",
    location: "A2.06 (Ged Baru)",
  },
  {
    start: [2021, 10, 6, 15, 0],
    end: [2021, 10, 6, 16, 40],
    title: "Jaringan Komputer B",
    location: "A2.06 (Ged Baru)",
  },
  {
    start: [2021, 10, 8, 10, 0],
    end: [2021, 10, 8, 11, 40],
    title: "Jaringan Komputer B",
    location: "A2.06 (Ged Baru)",
  },
];
